VIA_ENABLE = yes
ENCODER_MAP_ENABLE = yes
MOUSEKEY_ENABLE = yes

COSOLE_ENABLE = no
COMBO_ENABLE = no
AUDIO_ENABLE = no
LEADER_ENABLE = no
MIDI_ENABLE = no
UNICODE_ENABLE = no
RAW_ENABLE = no
NKRO_ENABLE = yes